# Generated by Django 5.1 on 2024-08-22 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('property', models.OneToOneField(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='property_app.property')),
            ],
        ),
    ]
