# Generated by Django 5.1 on 2024-08-23 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name_plural': 'Summeries'},
        ),
        migrations.AddField(
            model_name='summary',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
